In [1]:
round(1.23,1)

1.2

In [2]:
round(1.27,1)

1.3

In [3]:
round(-1.27,1)

-1.3

In [4]:
round(1.25361,3)

1.254

In [5]:
a=1627731

In [6]:
round(a,-1)

1627730

In [7]:
round(a,-2)

1627700

In [8]:
round(a,-3)

1628000

In [9]:
x=1.23456

In [10]:
format(x,'0.2f')

'1.23'

In [11]:
format(x,'0.3f')

'1.235'

In [12]:
'Value is {:0.3f}'.format(x)


'Value is 1.235'

In [13]:
a = 2.1

In [19]:
b = 4.2

In [20]:
c = a + b

In [21]:
c

6.300000000000001

In [22]:
c = round(c,2)

In [23]:
c

6.3

In [24]:
from decimal import Decimal

In [25]:
a = Decimal('4.2')

In [29]:
b = Decimal('2.1')

In [30]:
a + b

Decimal('6.3')

In [31]:
a + b == Decimal('6.3')

True

In [32]:
from decimal import localcontext

In [33]:
a = Decimal('1.3')

In [34]:
b= Decimal('1.7')

In [35]:
print(a/b)

0.7647058823529411764705882353


In [37]:
with localcontext() as ctx:
    ctx.prec = 3
    print(a/b)

0.765


In [38]:
with localcontext() as ctx:
    ctx.prec=50
    print(a/b)

0.76470588235294117647058823529411764705882352941176


In [39]:
nums = [1.28e+18, 1, -1.23e+18]

In [40]:
sum(nums)

5e+16

In [42]:
import math


In [43]:
math.fsum(nums)

5e+16

In [44]:
x = 1234.56789

In [45]:
format(x,'0.2f')

'1234.57'

In [46]:
format(x,'>10.1f')

'    1234.6'

In [47]:
format(x,'<10.1f')

'1234.6    '

In [48]:
format(x,'^10.1f')

'  1234.6  '

In [49]:
format(x,',')

'1,234.56789'

In [50]:
format(x,'0,.1f')

'1,234.6'

In [51]:
format(x,'e')

'1.234568e+03'

In [52]:
format(x,'0.2E')

'1.23E+03'

In [56]:
'The value is {:0,.2f}'.format(x)

'The value is 1,234.57'

In [57]:
format(x,'0.1f')

'1234.6'

In [58]:
format(-x,'0.1f')

'-1234.6'

In [59]:
swap_separators = {ord('.'):',',ord(','):'.'}

In [60]:
format(x,',')

'1,234.56789'

In [61]:
format(x,',').translate(swap_separators)

'1.234,56789'

In [62]:
'%0.2f' % x

'1234.57'

In [63]:
'%10.1f' % x


'    1234.6'

In [64]:
'%-10.1f'% x

'1234.6    '

In [65]:
#adding thousands separators arent supported using % operator


In [66]:
#3.4 working with Binary,Octal, and Hexadecimal integers

In [68]:
x= 1234

In [69]:
bin(x)

'0b10011010010'

In [70]:
oct(x)

'0o2322'

In [71]:
hex(x)

'0x4d2'

In [72]:
#can use the format() if you dont want the 0b,0o, or 0x

In [73]:
format(x,'b')

'10011010010'

In [74]:
format(x,'o')

'2322'

In [75]:
format(x,'x')

'4d2'

In [76]:
x=-1234


In [77]:
format(x,'b')

'-10011010010'

In [78]:
format(x,'o')

'-2322'

In [80]:
format(x,'x')

'-4d2'

In [81]:
#to show a 32-bit value

In [82]:
x=-1234

In [83]:
format(2**32 + x,'b')

'11111111111111111111101100101110'

In [85]:
format(2**32 + x,'x')

'fffffb2e'

In [87]:
int('4b2',16)

1202

In [88]:
int('10011010010',2)

1234

In [89]:
import os


In [91]:
os.chmod('script.py',0755)

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (4132201004.py, line 1)

In [92]:
os.chmod('script.py',0o755)

FileNotFoundError: [Errno 2] No such file or directory: 'script.py'

In [93]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [94]:
len(data)

16

In [95]:
int.from_bytes(data,'little')

69120565665751139577663547927094891008

In [97]:
int.from_bytes(data,'big')

94522842520747284487117727783387188

In [98]:
x=9452285250747284487117727783387188

In [99]:
x.to_bytes(16,'big')

b'\x00\x01\xd2\x08\x9c\xdf\xbd4\xd7\xde\x7f|\xea#\x004'

In [100]:
x.to_bytes(16,'little')

b'4\x00#\xea|\x7f\xde\xd74\xbd\xdf\x9c\x08\xd2\x01\x00'

In [101]:
data

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [102]:
import struct


In [103]:
hi, lo=struct.unpack('>QQ',data)

In [104]:
(hi << 64) + lo

94522842520747284487117727783387188

In [105]:
x=0x01020304

In [106]:
x.to_bytes(4,'big')

b'\x01\x02\x03\x04'

In [107]:
x.to_bytes(4,'little')

b'\x04\x03\x02\x01'

In [108]:
x = 523 ** 23

In [109]:
x

335381300113661875107536852714019056160355655333978849017944067

In [110]:
x.to_bytes(16,'little')

OverflowError: int too big to convert

In [112]:
x.bit_length()

208

In [113]:
nbytes, rem = divmod(x.bit_length(),8)

In [114]:
if rem:
    nbytes += 1

In [115]:
x.to_bytes(nbytes,'little')

b'\x03X\xf1\x82iT\x96\xac\xc7c\x16\xf3\xb9\xcf\x18\xee\xec\x91\xd1\x98\xa2\xc8\xd9R\xb5\xd0'

In [116]:
#3.6 performing complex-valued Math 

In [117]:
a = complex(2,4)

In [118]:
b= 3 - 5j

In [119]:
a

(2+4j)

In [120]:
b

(3-5j)

In [121]:
a.real

2.0

In [122]:
a.imag

4.0

In [123]:
a.conjugate()

(2-4j)

In [124]:
a + b

(5-1j)

In [125]:
a * b

(26+2j)

In [126]:
a / b

(-0.4117647058823529+0.6470588235294118j)

In [127]:
abs(a)

4.47213595499958

In [128]:
import cmath


In [129]:
cmath.sin(a)

(24.83130584894638-11.356612711218174j)

In [130]:
cmath.cos(a)

(-11.36423470640106-24.814651485634187j)

In [131]:
cmath.exp(a)

(-4.829809383269385-5.5920560936409816j)

In [132]:
import numpy as np

In [133]:
a = np.array([2+3j, 4+5j, 6-7j, 8+9j])

In [134]:
a

array([2.+3.j, 4.+5.j, 6.-7.j, 8.+9.j])

In [135]:
a + 2

array([ 4.+3.j,  6.+5.j,  8.-7.j, 10.+9.j])

In [136]:
np.sin(a)

array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
       -153.20827755-526.47684926j, 4008.42651446-589.49948373j])

In [137]:
cmath.sqrt(-1)

1j

In [138]:
#3.7 Working with infity and NaNs


In [139]:
a = float('inf')

In [140]:
b=float('-inf')

In [141]:
c=float('nan')

In [142]:
a


inf

In [143]:
b

-inf

In [144]:
c

nan

In [145]:
math.isinf(a)

True

In [146]:
math.isnan(c)

True

In [147]:
a = float('inf')

In [148]:
a + 45

inf

In [149]:
a * 10

inf

In [150]:
10/ a

0.0

In [151]:
a/a

nan

In [152]:
b = float('-inf')

In [153]:
a + b

nan

In [154]:
c = float('nan')

In [155]:
c + 23

nan

In [156]:
c/2

nan

In [157]:
c * 2

nan

In [158]:
math.sqrt(c)

nan

In [159]:
d = float('nan')

In [160]:
c == d

False

In [161]:
c is d

False

In [162]:
math.isnan(c)

True

In [163]:
#3.8 calculating with fractions 

In [164]:
from fractions import Fraction

In [165]:
a = Fraction(5,4)

In [166]:
b= Fraction(7,16)

In [167]:
print(a + b)

27/16


In [168]:
print(a * b)

35/64


In [169]:
#getting numerator/denominator

In [170]:
c = a * b

In [171]:
c.numerator

35

In [172]:
c.denominator

64

In [173]:
#converting to a float

In [174]:
float(c)

0.546875

In [175]:
#limiting the denominator of a value

In [177]:
print(c.limit_denominator(8))

4/7


In [178]:
#converting a float to a fraction

In [179]:
x= 3.75

In [180]:
y = Fraction(*x.as_integer_ratio())

In [181]:
y

Fraction(15, 4)

In [182]:
#3.9 Calculating with large numberial arrays 

In [183]:
#python lists

In [184]:
x= [1,2,3,4]

In [185]:
y=[5,6,7,8]

In [186]:
x * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [187]:
x + 10

TypeError: can only concatenate list (not "int") to list

In [188]:
x + y

[1, 2, 3, 4, 5, 6, 7, 8]

In [189]:
#Numpy arrays

In [190]:
import numpy as np

In [191]:
ax = np.array([1,2,3,4])

In [192]:
ay= np.array([5,6,7,8])

In [193]:
ax + 10

array([11, 12, 13, 14])

In [194]:
ax + ay

array([ 6,  8, 10, 12])

In [195]:
ax * ay

array([ 5, 12, 21, 32])

In [196]:
#polynomial

In [197]:
def f(x):
    return 3*x**2 - 2*x + 7

In [198]:
f(ax)

array([ 8, 15, 28, 47])

In [199]:
np.sqrt(ax)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [200]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [201]:
#two dimentionsal grid of 10,0000 by 10,000 floats 

In [202]:
grid = np.zeros(shape=(10000,10000),dtype=float)

In [203]:
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [204]:
grid += 10

In [205]:
grid

array([[10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       ...,
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.]])

In [206]:
np.sin(grid)

array([[-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       ...,
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111]])

In [207]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [208]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [209]:
#select row 1

In [210]:
a[1]

array([5, 6, 7, 8])

In [211]:
#select column 1

In [212]:
a[:,1]

array([ 2,  6, 10])

In [213]:
#select a subregion and change it 

In [214]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [215]:
a[1:3,1:3] += 10

In [216]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [217]:
#Broadcast a row vector across an operation on all rows

In [218]:
a +[100,101,102,103]

array([[101, 103, 105, 107],
       [105, 117, 119, 111],
       [109, 121, 123, 115]])

In [219]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [220]:
#conditional assignment on an array

In [221]:
np.where(a <10,a,10)

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

In [222]:
#3.10 performing matrix and linear algebra calculations 

In [223]:
import numpy as np

In [225]:
m= np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])

In [226]:
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [227]:
#return transpose

In [228]:
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [229]:
#return inverse

In [230]:
m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [231]:
#create a vector and multiply

In [233]:
v = np.matrix([[2],[3],[4]])

In [234]:
v

matrix([[2],
        [3],
        [4]])

In [235]:
m * v

matrix([[ 8],
        [32],
        [ 2]])

In [236]:
import numpy.linalg

In [237]:
#Determinant

In [238]:
numpy.linalg.det(m)

-229.99999999999983

In [239]:
#Eligenvalues

In [240]:
numpy.linalg.eigvals(m)

array([-13.11474312,   2.75956154,   6.35518158])

In [241]:
#solve for x in mx=v 

In [242]:
x = numpy.linalg.solve(m,v)

In [243]:
x

matrix([[0.96521739],
        [0.17391304],
        [0.46086957]])

In [244]:
m*x

matrix([[2.],
        [3.],
        [4.]])

In [245]:
v

matrix([[2],
        [3],
        [4]])

In [246]:
#3.11 Picking things at random 

In [247]:
import random

In [248]:
values = [1,2,3,4,5,6]

In [249]:
random.choice(values)

3

In [250]:
random.choice(values)

2

In [252]:
random.sample(values,2)

[1, 4]

In [253]:
random.sample(values,3)

[6, 5, 2]

In [254]:
random.shuffle(values)

In [255]:
values

[1, 3, 6, 5, 2, 4]

In [256]:
random.shuffle(values)

In [257]:
values

[2, 1, 3, 4, 6, 5]

In [ ]:
#to produce random integers 

In [258]:
random.randint(0,10)

7

In [260]:
random.randint(0,10)

5

In [ ]:
# to get N random-bits expressed as an integer

In [263]:
random.getrandbits(200)

1328784624416230751754828447470718360641497351043656988290419

In [265]:
# to produce floating-point values in the reange 0 to 1 

In [264]:
random.random()

0.08712844319408197

In [266]:
random.random()

0.6224101917257926

In [267]:
#to get N random-bits expressed as an integer, use random.getrandbits()

In [268]:
random.getrandbits(200)

957956317110158826130548958533101471073993151783193085410602

~~~
From this lab, I learned how to perform mathematical calculations with integers floating-point numbers and accurate decimal calculations.  I also learned how to format numbers for output using the format() syntax.
When working with binary,octal, and hexadecimal integers you have the ability to convert them using bin(),oct,(), or hex().  
I learned how to pack and unpack large integers from bytes using the int.from_bytes syntax. 
I was also introduced to performing complex-valued Math, for example sines, cosines, and squareroots. 
They are mostly done using the cmath module. I was exposed to working with infinity and Nans. 
NaNs stands for not a number. They are created using the float() syntax. 
I dealt with calculating fractions using the fraction module with the syntax Fraction(). 
Then I learned how to calculate with large numerical arrays which are better used with the numpy module. 
The numpy module is compatible with performing matrix and linear algebra calculations. With matrix, you use the np.matrix syntax. 
Finally, I learned how to pick integers at random using random.choice(),random.sample() and random.randint()

~~~
